apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.0.0-dev+build.8270
  name: main-i-0fb11-6beb6c7
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-0fb11-6beb6c7
  eksaVersion: v0.0.0-dev+build.8270
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.28"
  machineHealthCheck:
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: main-i-0fb11-6beb6c7
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-0fb11-6beb6c7
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: quick-e2e-test-ea545ed6-3a6e-42dc-975a-64f873ac2219-2
  clusterConfigPath: quick-e2e-test-ea545ed6-3a6e-42dc-975a-64f873ac2219-2
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/quick-e2e-test-ea545ed6-3a6e-42dc-975a-64f873ac2219-2.git
  systemNamespace: default

---
